# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: CmdLine@2
  inputs:
    script: sudo apt-get install libgtkglextmm-x11-1.2 libgstreamermm-1.0-dev libdc1394-22-dev -y

- task: CMake@1
  inputs:
    cmakeArgs: $(Build.SourcesDirectory)

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: $(Build.SourcesDirectory)\build\**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: CMLNSrc